# Site settings
title: CenCal Ruby User Group
email: contact@cencalruby.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the CenCal Ruby user group site. We are a group of
  developers in the Central California based in Fresno, CA.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.cencalruby.org" # the base hostname & protocol for your site
twitter_username: cencalruby
github_username:  cencalruby

# Build settings
markdown: kramdown
